using System.ComponentModel.DataAnnotations;

namespace AlgoaBayBMT.Shared.Models
{
    // ─────────────────────────────────────────────────────────────────
    // Operator billing account (kept lightweight)
    // ─────────────────────────────────────────────────────────────────
    public class OperatorBillingAccount
    {
        public int Id { get; set; }

        public int BunkerOperatorId { get; set; }
        public BunkerOperator BunkerOperator { get; set; } = null!;

        [StringLength(80)]
        public string? AccountNumber { get; set; }

        [StringLength(200)]
        public string? BillingContactName { get; set; }

        [EmailAddress, StringLength(254)]
        public string? BillingEmail { get; set; }

        [Phone, StringLength(50)]
        public string? BillingPhone { get; set; }

        [StringLength(500)]
        public string? BillingAddress { get; set; }

        [StringLength(20)]
        public string Currency { get; set; } = "ZAR";

        public int PaymentTermsDays { get; set; } = 30;

        public bool IsActive { get; set; } = true;

        public DateTime CreatedOnUtc { get; set; } = DateTime.UtcNow;
        public string? CreatedByUserId { get; set; }
        public DateTime? ModifiedOnUtc { get; set; }
        public string? ModifiedByUserId { get; set; }
    }

    public enum InvoiceStatus
    {
        Draft = 0,
        Issued = 1,
        Paid = 2,
        Cancelled = 3,
        Overdue = 4
    }

    public class Invoice
    {
        public int Id { get; set; }

        [Required, StringLength(50)]
        public string InvoiceNumber { get; set; } = string.Empty;

        public int? OperatorBillingAccountId { get; set; }
        public OperatorBillingAccount? OperatorBillingAccount { get; set; }

        public int BunkerOperatorId { get; set; }
        public BunkerOperator BunkerOperator { get; set; } = null!;

        // Optional crew/vessel links for traceability
        public int? CrewMemberId { get; set; }
        public CrewMember? CrewMember { get; set; }

        public int? VesselId { get; set; }
        public Vessel? Vessel { get; set; }

        public DateTime InvoiceDateUtc { get; set; } = DateTime.UtcNow;
        public DateTime? DueDateUtc { get; set; }

        [StringLength(20)]
        public string Currency { get; set; } = "ZAR";

        public decimal SubTotal { get; set; }
        public decimal TaxAmount { get; set; }
        public decimal TotalAmount { get; set; }

        public InvoiceStatus Status { get; set; } = InvoiceStatus.Draft;

        [StringLength(2000)]
        public string? Notes { get; set; }

        // Audit
        public DateTime CreatedOnUtc { get; set; } = DateTime.UtcNow;
        public string? CreatedByUserId { get; set; }
        public DateTime? ModifiedOnUtc { get; set; }
        public string? ModifiedByUserId { get; set; }
        public bool IsDeleted { get; set; }
        public DateTime? DeletedOnUtc { get; set; }
        public string? DeletedByUserId { get; set; }

        public ICollection<InvoiceLineItem> LineItems { get; set; } = new List<InvoiceLineItem>();
    }

    public class InvoiceLineItem
    {
        public int Id { get; set; }

        public int InvoiceId { get; set; }
        public Invoice Invoice { get; set; } = null!;

        [Required, StringLength(500)]
        public string Description { get; set; } = string.Empty;

        public decimal Quantity { get; set; } = 1m;
        public decimal UnitPrice { get; set; }
        public decimal LineTotal { get; set; }

        // Optional course link if line was generated by compliance auto-assignment
        public Guid? RelatedCourseId { get; set; }
        public Course? RelatedCourse { get; set; }
    }

    // ─────────────────────────────────────────────────────────────────
    // Notifications (in-app + email queue)
    // ─────────────────────────────────────────────────────────────────
    public enum NotificationChannel
    {
        InApp = 0,
        Email = 1,
        Both = 2
    }

    public enum NotificationCategory
    {
        CertificateExpiry = 0,
        Compliance = 1,
        TrainingAssignment = 2,
        Billing = 3,
        General = 99
    }

    public enum NotificationStatus
    {
        Pending = 0,
        Sent = 1,
        Read = 2,
        Failed = 3
    }

    public class NotificationMessage
    {
        public int Id { get; set; }

        public NotificationChannel Channel { get; set; } = NotificationChannel.InApp;
        public NotificationCategory Category { get; set; }
        public NotificationStatus Status { get; set; } = NotificationStatus.Pending;

        [Required, StringLength(450)]
        public string RecipientUserId { get; set; } = string.Empty;

        [StringLength(254)]
        public string? RecipientEmail { get; set; }

        [StringLength(200)]
        public string? RecipientDisplayName { get; set; }

        [Required, StringLength(300)]
        public string Subject { get; set; } = string.Empty;

        [Required, StringLength(4000)]
        public string Body { get; set; } = string.Empty;

        // Optional links
        public int? RelatedCrewMemberId { get; set; }
        public int? RelatedVesselId { get; set; }
        public int? RelatedComplianceResultId { get; set; }
        public int? RelatedInvoiceId { get; set; }
        public int? RelatedExpiryEventId { get; set; }

        public DateTime CreatedOnUtc { get; set; } = DateTime.UtcNow;
        public DateTime? SentOnUtc { get; set; }
        public DateTime? ReadOnUtc { get; set; }

        [StringLength(2000)]
        public string? FailureReason { get; set; }

        public int RetryCount { get; set; }
    }
}
