<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-AlgoaBayBMT-0ddb72ca-a8da-4f21-b3e8-fdccfe4a47e9</UserSecretsId>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="10.0.7" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.7">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
	    <PackageReference Include="Syncfusion.Blazor.Grid" Version="33.2.5" />
    <PackageReference Include="Syncfusion.Blazor.ImageEditor" Version="33.2.5" />
    <PackageReference Include="Syncfusion.Blazor.InPlaceEditor" Version="33.2.5" />
    <PackageReference Include="Syncfusion.Blazor.Calendars" Version="33.2.5" />
    <PackageReference Include="Syncfusion.Blazor.RichTextEditor" Version="33.2.5" />
    <PackageReference Include="Syncfusion.Blazor.Schedule" Version="33.2.5" />
    <PackageReference Include="Syncfusion.Blazor.DropDowns" Version="33.2.5" />
    <PackageReference Include="Syncfusion.Blazor.MultiColumnComboBox" Version="33.2.5" />
    <PackageReference Include="Syncfusion.Blazor.Popups" Version="33.2.5" />
    <PackageReference Include="Syncfusion.Blazor.Layouts" Version="33.2.5" />
    <PackageReference Include="Syncfusion.Blazor.Cards" Version="33.2.5" />
    <PackageReference Include="Syncfusion.Blazor.Inputs" Version="33.2.5" />
    <PackageReference Include="Syncfusion.Blazor.Buttons" Version="33.2.5" />
    <PackageReference Include="Syncfusion.Blazor.Navigations" Version="33.2.5" />
    <PackageReference Include="Syncfusion.Blazor.Spinner" Version="33.2.5" />
    <PackageReference Include="Syncfusion.Blazor.Notifications" Version="33.2.5" />
    <PackageReference Include="Syncfusion.Blazor.DataForm" Version="33.2.5" />
    <PackageReference Include="Syncfusion.Blazor.Themes" Version="33.2.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AlgoaBayBMT.Shared\AlgoaBayBMT.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="wwwroot\uploads\**\*" />
    <None Include="wwwroot\uploads\**\*" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Components\Home\" />
  </ItemGroup>
  
  

</Project>
